name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:
    types: [checks_requested]

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        sandbox:
          [
            react/latest/react-19-vite-ts,
            react/latest/react-19-vite,
            react/latest/react-18-vite-ts,
            react/latest/react-18-vite,
            react/latest/react-17-vite,
            react/latest/react-16-vite,
          ]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Use Node.js 20.x
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: "20.x"
      - name: Install dependencies
        run: |
          cd ${{ matrix.sandbox }}
          yarn install
      - name: Build project
        run: |
          cd ${{ matrix.sandbox }}
          yarn build

  deploy-preview:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        sandbox:
          [
            react/latest/react-19-vite-ts,
            react/latest/react-19-vite,
            react/latest/react-18-vite-ts,
            react/latest/react-18-vite,
            react/latest/react-17-vite,
            react/latest/react-16-vite,
          ]
    environment:
      name: ${{ matrix.sandbox }}
      url: https://stackblitz.com/github/carbon-design-system/sandboxes/tree/${{ github.sha }}/${{ matrix.sandbox }}/
    steps:
      - name: Generate job summary
        run: |
          echo "### Sandbox created with SHA ${{ github.sha }} :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "[![Open in StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/github/carbon-design-system/sandboxes/tree/${{ github.sha }}/${{ matrix.sandbox }}/)" >> $GITHUB_STEP_SUMMARY
