name: daily builds

on:
  workflow_dispatch:
  schedule:
    # Run once daily at 00:00 UTC, ~7/8PM CST
    - cron: "0 0 * * *"

jobs:
  builds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sandbox:
          [
            react/latest/react-19-vite-ts,
            react/latest/react-19-vite,
            react/latest/react-18-vite-ts,
            react/latest/react-18-vite,
            react/latest/react-17-vite,
            react/latest/react-16-vite,
          ]
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - name: Use Node.js 20.x
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "22.x"
      - name: Install dependencies
        run: |
          cd ${{ matrix.sandbox }}
          yarn install
      - name: Build project
        run: |
          cd ${{ matrix.sandbox }}
          yarn build
