name: daily builds

on:
  workflow_dispatch:
  schedule:
    # Run once daily at 00:00 UTC, ~7/8PM CST
    - cron: "0 0 * * *"

jobs:
  builds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sandbox:
          [
            react/latest/react-19-vite-ts,
            react/latest/react-19-vite,
            react/latest/react-18-vite-ts,
            react/latest/react-18-vite,
            react/latest/react-17-vite,
            react/latest/react-16-vite,
          ]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Use Node.js 20.x
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: "22.x"
      - name: Install dependencies
        run: |
          cd ${{ matrix.sandbox }}
          yarn install
      - name: Build project
        run: |
          cd ${{ matrix.sandbox }}
          yarn build
