name: daily builds

on:
  workflow_dispatch:
  schedule:
    # Run once daily at 00:00 UTC, ~7/8PM CST
    - cron: "0 0 * * *"

jobs:
  builds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sandbox:
          [
            react/latest/react-19-vite-ts,
            react/latest/react-19-vite,
            react/latest/react-18-vite-ts,
            react/latest/react-18-vite,
            react/latest/react-17-vite,
            react/latest/react-16-vite,
          ]
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Use Node.js 20.x
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: "20.x"
      - name: Install dependencies
        run: |
          cd ${{ matrix.sandbox }}
          yarn install
      - name: Build project
        run: |
          cd ${{ matrix.sandbox }}
          yarn build
